### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by jordanj334** [GitMocha/mocha-txAdminLogs#1]
Just installed as a resource set the webhook in line 109 of server/sv_main.lua and ensured it then restarted the server and im not getting any logs sent as webhooks there are no errors or anything out of ordinary in either ingame console or tx live console, any suggestions as your tx logs are the only ones i have found that have all the menu functions particularly the toggling names and spectating.

thanks

**Comment by jordanj334** [comment]
[script:mocha_txAdmin] SCRIPT ERROR: @mocha_txAdminLogs/server/sv_main.lua:105: attempt to call a nil value (global 'logger')
sorry here is what it says in logs

**Comment by GitMocha** [comment]
> [script:mocha_txAdmin] SCRIPT ERROR: @mocha_txAdminLogs/server/sv_main.lua:105: attempt to call a nil value (global 'logger') sorry here is what it says in logs

I'll take a look now and get back to you.

**Comment by GitMocha** [comment]
> [script:mocha_txAdmin] SCRIPT ERROR: @mocha_txAdminLogs/server/sv_main.lua:105: attempt to call a nil value (global 'logger') sorry here is what it says in logs

Tested, seems to be working fine. No errors. Make sure your framework is up to date, make sure you have add your discord channel webhook to smallresources - server - logs.lua and webhook name to txadmin line 109 then restart both. Picture below with todays date showing it working :) 

![Screenshot 2024-05-15 184042](https://github.com/GitMocha/mocha-txAdminLogs/assets/97256967/baa1ebca-e6d3-40eb-a204-e0812607ed60)
